version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "image-resizer"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1dravb4zak9ny"
s3_prefix = "image-resizer"
region = "ap-northeast-2"
capabilities = "CAPABILITY_IAM"
image_repositories = []
